/** Every value below resolves to a token declared once in styles/tokens.css. */
export default {content: [
  './index.html',
  './src/**/*.{js,ts,jsx,tsx}'
],
  theme: {
    extend: {
      colors: {
        void: 'var(--color-void)',
        surface: 'var(--color-surface)',
        raised: 'var(--color-surface-raised)',
        sunken: 'var(--color-surface-sunken)',
        line: 'var(--color-line)',
        'line-strong': 'var(--color-line-strong)',
        fg: 'var(--color-fg)',
        'fg-muted': 'var(--color-fg-muted)',
        'fg-faint': 'var(--color-fg-faint)',
        ink: 'var(--color-ink)',
        accent: 'var(--color-accent)',
        'accent-strong': 'var(--color-accent-strong)',
        'accent-ink': 'var(--color-accent-ink)',
        'accent-soft': 'var(--color-accent-soft)',
        'accent-line': 'var(--color-accent-line)',
        pass: 'var(--color-pass)',
        'pass-soft': 'var(--color-pass-soft)',
        warning: 'var(--color-warning)',
        'warning-soft': 'var(--color-warning-soft)',
        'warning-line': 'var(--color-warning-line)',
        danger: 'var(--color-danger)',
        'danger-soft': 'var(--color-danger-soft)',
        'danger-line': 'var(--color-danger-line)',
        info: 'var(--color-info)',
        'info-soft': 'var(--color-info-soft)',
        'info-line': 'var(--color-info-line)',
        paper: 'var(--color-paper)',
      },
      fontFamily: {
        sans: 'var(--font-sans)',
        mono: 'var(--font-mono)',
      },
      fontSize: {
        '2xs': 'var(--text-2xs)',
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        md: 'var(--text-md)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
      },
      letterSpacing: {
        label: 'var(--tracking-label)',
        tightest: 'var(--tracking-tight)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      spacing: {
        0.5: 'var(--space-0-5)',
        1: 'var(--space-1)',
        1.5: 'var(--space-1-5)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
      },
      boxShadow: {
        card: 'var(--shadow-card)',
      },
      maxWidth: {
        console: 'var(--width-console)',
        page: 'var(--width-page)',
      },
      width: {
        rail: 'var(--width-rail)',
      },
      transitionTimingFunction: {
        out: 'var(--ease-out)',
      },
    },
  },
};
