"""Record real engine responses as the frontend's offline fixtures.

The console ships with mock data so it can run standalone. Hand-written mocks drift
from the real contract and, worse, invent crew and pairings that do not exist. These
fixtures are recorded from the live deterministic engine instead, so offline mode shows
the same facts the backend would return.

    python scripts/record_fixtures.py
"""
from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.alerts.sentinel import build_alerts  # noqa: E402
from app.api import envelope  # noqa: E402
from app.db.repository import get_repository  # noqa: E402
from app.domain.time_utils import time_on_date  # noqa: E402
from app.engine.state import BASE_STATE  # noqa: E402
from app.fallback import structured_query  # noqa: E402
from app.services import actions as A  # noqa: E402
from app.services.scorecard import run_scorecard  # noqa: E402

OUT = Path(__file__).resolve().parents[2] / "frontend" / "src" / "mocks"
HEADER = (
    "// GENERATED by backend/scripts/record_fixtures.py -- do not hand-edit.\n"
    "// Recorded from the live deterministic engine, so offline mode shows real\n"
    "// dataset facts rather than invented ones. Regenerate after engine changes.\n"
)


def envelope_for(repo, question: str) -> dict:
    result = structured_query.route(repo, question)
    return envelope.from_tool(question, "recorded", result, 0)


# Envelope fields the TS contract marks optional: an absent key type-checks, an
# explicit null does not. Everything else stays -- RuleCheck.margin, for instance, is
# required AND nullable, so stripping its null would break the type.
OPTIONAL_ENVELOPE_KEYS = (
    "table", "impact", "options", "relaxations", "alerts", "before_after",
    "notification",
)


def prune(value):
    if isinstance(value, dict):
        return {
            k: v for k, v in value.items()
            if not (v is None and k in OPTIONAL_ENVELOPE_KEYS)
        }
    return value


def ts(name: str, type_name: str, value) -> str:
    return (
        f"export const {name}: {type_name} = "
        + json.dumps(prune(value), indent=2, ensure_ascii=False, default=str)
        + ";\n"
    )


def main() -> None:
    repo = get_repository()

    reserves = envelope_for(repo, "Who is on reserve at BLR on 2026-09-15?")
    follow_up = envelope_for(repo, "What is C-3310's reserve on-call window and reachability?")
    cannot = envelope_for(repo, "What is the meaning of life?")
    simulate = envelope.from_tool(
        "If I move Captain C-2087 onto P-2291, does anyone breach a duty limit?",
        "recorded", A.assess_assignment(repo, "C-2087", "P-2291"), 0,
    )
    impact = envelope.from_tool(
        "Captain C-1042 called in sick on 15 Sep. Which flights are uncrewed?",
        "recorded",
        A.analyse_impact(
            repo, BASE_STATE.with_crew_unavailable("C-1042", "sick"), date(2026, 9, 15)
        ), 0,
    )
    recommend = envelope.from_tool(
        "Captain C-1042 is out for P-2291. What should I do?",
        "recorded",
        A.recommend_cover(repo, "P-2291", "Captain", crew_out="C-1042"), 0,
    )
    # a delay-driven case, which is where near-miss and duty-splitting show up
    delayed = BASE_STATE
    for flight in repo.flights_by_date["2026-09-16"]:
        if flight.aircraft == "VT-DXA":
            delayed = delayed.with_flight_delay(flight.flight_id, 1.5)
    relaxation = envelope.from_tool(
        "VT-DXA is delayed 90 minutes on 16 Sep. What should Crew Control do?",
        "recorded", A.recover_from_state(repo, delayed), 0,
    )
    alerts = envelope.from_tool(
        "Anything I should worry about tomorrow?", "recorded",
        build_alerts(repo, date(2026, 9, 15)), 0,
    )
    card = run_scorecard(repo)

    # MCP connection details. Paths are placeholders in the fixture: the live endpoint
    # serves the real ones for whichever machine is running, and baking this machine's
    # paths into a committed file would be wrong for everyone else.
    from app.llm.tools import tool_catalogue

    mcp = {
        "server_name": "crew-ops",
        "transport": "stdio",
        "command": "<repo>/backend/.venv/Scripts/python.exe",
        "args": ["<repo>/backend/mcp_server/index.py"],
        "config_json": json.dumps(
            {"mcpServers": {"crew-ops": {
                "command": "<repo>/backend/.venv/Scripts/python.exe",
                "args": ["<repo>/backend/mcp_server/index.py"]}}},
            indent=2,
        ),
        "config_path": {
            "windows": r"%APPDATA%\Claude\claude_desktop_config.json",
            "macos": "~/Library/Application Support/Claude/claude_desktop_config.json",
        },
        "tools": tool_catalogue(),
    }

    (OUT / "chat.ts").write_text(
        HEADER
        + "\nimport type { AdvisorResponse } from '../types/api';\n"
        + "import { mockImpactResponse } from './impact';\n"
        + "import { mockRecommendResponse, mockRelaxationResponse } from './recommend';\n"
        + "import { mockAlertsResponse } from './alerts';\n\n"
        + ts("mockReserveTable", "AdvisorResponse", reserves) + "\n"
        + ts("mockFollowUp", "AdvisorResponse", follow_up) + "\n"
        + ts("mockCannotAnswer", "AdvisorResponse", cannot) + "\n"
        + ts("mockSimulateResponse", "AdvisorResponse", simulate) + "\n"
        + RESOLVER,
        encoding="utf-8",
    )
    (OUT / "impact.ts").write_text(
        HEADER + "\nimport type { AdvisorResponse } from '../types/api';\n\n"
        + ts("mockImpactResponse", "AdvisorResponse", impact),
        encoding="utf-8",
    )
    (OUT / "recommend.ts").write_text(
        HEADER + "\nimport type { AdvisorResponse } from '../types/api';\n\n"
        + ts("mockRecommendResponse", "AdvisorResponse", recommend) + "\n"
        + ts("mockRelaxationResponse", "AdvisorResponse", relaxation),
        encoding="utf-8",
    )
    (OUT / "alerts.ts").write_text(
        HEADER + "\nimport type { Alert, AdvisorResponse } from '../types/api';\n\n"
        + ts("mockAlertItems", "Alert[]", alerts.get("alerts") or []) + "\n"
        + ts("mockAlertsResponse", "AdvisorResponse", alerts),
        encoding="utf-8",
    )
    (OUT / "mcp.ts").write_text(
        HEADER + "\nimport type { McpInfo } from '../types/api';\n\n"
        + ts("mockMcpInfo", "McpInfo", mcp),
        encoding="utf-8",
    )
    (OUT / "scorecard.ts").write_text(
        HEADER + "\nimport type { ScorecardResponse } from '../types/api';\n\n"
        + ts("mockScorecard", "ScorecardResponse", card),
        encoding="utf-8",
    )

    print(f"Recorded fixtures into {OUT}")
    for name in ("chat", "impact", "recommend", "alerts", "scorecard", "mcp"):
        print(f"  {name}.ts")


RESOLVER = """
/** Routes a typed question to the closest recorded fixture. */
export function resolveMockChat(question: string): AdvisorResponse {
  const q = question.toLowerCase();
  if (/(sick|out for|unavailable|what should i do|options|recommend)/.test(q)) {
    return { ...mockRecommendResponse, query: question };
  }
  if (/(delay|delayed|fdp)/.test(q)) {
    return { ...mockRelaxationResponse, query: question };
  }
  if (/(uncrewed|uncovered|impact|affected|closed|closure)/.test(q)) {
    return { ...mockImpactResponse, query: question };
  }
  if (/(worry|risky|alert|briefing|watch)/.test(q)) {
    return { ...mockAlertsResponse, query: question };
  }
  if (/reserve/.test(q)) return { ...mockReserveTable, query: question };
  if (/(window|reachab|base|rating|profile)/.test(q)) {
    return { ...mockFollowUp, query: question };
  }
  return { ...mockCannotAnswer, query: question };
}
"""


if __name__ == "__main__":
    main()
