// GENERATED by backend/scripts/record_fixtures.py -- do not hand-edit.
// Recorded from the live deterministic engine, so offline mode shows real
// dataset facts rather than invented ones. Regenerate after engine changes.

import type { Alert, AdvisorResponse } from '../types/api';

export const mockAlertItems: Alert[] = [
  {
    "id": "cert-C-5417-recurrent_training",
    "severity": "critical",
    "subject": "C-5417",
    "subject_type": "crew",
    "message": "Cabin Crew C-5417 - recurrent_training expires 2026-09-17 (2 days) and they are rostered beyond that date.",
    "date": "2026-09-15"
  },
  {
    "id": "cert-C-2087-licence",
    "severity": "warning",
    "subject": "C-2087",
    "subject_type": "crew",
    "message": "Captain C-2087 - licence expires 2026-09-18 (3 days) - no duty rostered past expiry.",
    "date": "2026-09-15"
  },
  {
    "id": "cert-C-2091-medical_class1",
    "severity": "warning",
    "subject": "C-2091",
    "subject_type": "crew",
    "message": "Captain C-2091 - medical_class1 expires 2026-09-23 (8 days) - no duty rostered past expiry.",
    "date": "2026-09-15"
  },
  {
    "id": "cert-C-3116-dangerous_goods",
    "severity": "warning",
    "subject": "C-3116",
    "subject_type": "crew",
    "message": "First Officer C-3116 - dangerous_goods expires 2026-09-28 (13 days) - no duty rostered past expiry.",
    "date": "2026-09-15"
  },
  {
    "id": "duty-C-2087",
    "severity": "warning",
    "subject": "C-2087",
    "subject_type": "crew",
    "message": "Captain C-2087 (BLR) is at 51.83h of the 60h 7-day duty limit - 8.17h headroom left.",
    "date": "2026-09-15"
  },
  {
    "id": "pool-DEL-Cabin Crew",
    "severity": "warning",
    "subject": "DEL Cabin Crew",
    "subject_type": "pool",
    "message": "Only 1 cabin crew reserve on call at DEL on 2026-09-15.",
    "date": "2026-09-15"
  },
  {
    "id": "pool-DEL-Captain",
    "severity": "warning",
    "subject": "DEL Captain",
    "subject_type": "pool",
    "message": "Only 1 captain reserve on call at DEL on 2026-09-15.",
    "date": "2026-09-15"
  },
  {
    "id": "pool-DEL-First Officer",
    "severity": "warning",
    "subject": "DEL First Officer",
    "subject_type": "pool",
    "message": "Only 1 first officer reserve on call at DEL on 2026-09-15.",
    "date": "2026-09-15"
  },
  {
    "id": "pool-DEL-Senior Cabin Crew",
    "severity": "warning",
    "subject": "DEL Senior Cabin Crew",
    "subject_type": "pool",
    "message": "Only 1 senior cabin crew reserve on call at DEL on 2026-09-15.",
    "date": "2026-09-15"
  },
  {
    "id": "risk-C-1042",
    "severity": "info",
    "subject": "C-1042",
    "subject_type": "crew",
    "message": "Captain C-1042 carries a provided disruption-risk score of 0.78: short-rest pattern over last 14 days; two fatigue reports this month.",
    "date": "2026-09-15"
  },
  {
    "id": "risk-C-3940",
    "severity": "info",
    "subject": "C-3940",
    "subject_type": "crew",
    "message": "Captain C-3940 carries a provided disruption-risk score of 0.71: elevated sick-call likelihood: cluster pattern at base.",
    "date": "2026-09-15"
  }
];

export const mockAlertsResponse: AdvisorResponse = {
  "query": "Anything I should worry about tomorrow?",
  "intent": "recorded",
  "tier": 2,
  "answer_text": "11 operational signals for 2026-09-15: 1 critical, 8 warning, 2 informational.",
  "confidence": "high",
  "grounding": {
    "verified": true,
    "unverified_claims": []
  },
  "alerts": [
    {
      "id": "cert-C-5417-recurrent_training",
      "severity": "critical",
      "subject": "C-5417",
      "subject_type": "crew",
      "message": "Cabin Crew C-5417 - recurrent_training expires 2026-09-17 (2 days) and they are rostered beyond that date.",
      "date": "2026-09-15"
    },
    {
      "id": "cert-C-2087-licence",
      "severity": "warning",
      "subject": "C-2087",
      "subject_type": "crew",
      "message": "Captain C-2087 - licence expires 2026-09-18 (3 days) - no duty rostered past expiry.",
      "date": "2026-09-15"
    },
    {
      "id": "cert-C-2091-medical_class1",
      "severity": "warning",
      "subject": "C-2091",
      "subject_type": "crew",
      "message": "Captain C-2091 - medical_class1 expires 2026-09-23 (8 days) - no duty rostered past expiry.",
      "date": "2026-09-15"
    },
    {
      "id": "cert-C-3116-dangerous_goods",
      "severity": "warning",
      "subject": "C-3116",
      "subject_type": "crew",
      "message": "First Officer C-3116 - dangerous_goods expires 2026-09-28 (13 days) - no duty rostered past expiry.",
      "date": "2026-09-15"
    },
    {
      "id": "duty-C-2087",
      "severity": "warning",
      "subject": "C-2087",
      "subject_type": "crew",
      "message": "Captain C-2087 (BLR) is at 51.83h of the 60h 7-day duty limit - 8.17h headroom left.",
      "date": "2026-09-15"
    },
    {
      "id": "pool-DEL-Cabin Crew",
      "severity": "warning",
      "subject": "DEL Cabin Crew",
      "subject_type": "pool",
      "message": "Only 1 cabin crew reserve on call at DEL on 2026-09-15.",
      "date": "2026-09-15"
    },
    {
      "id": "pool-DEL-Captain",
      "severity": "warning",
      "subject": "DEL Captain",
      "subject_type": "pool",
      "message": "Only 1 captain reserve on call at DEL on 2026-09-15.",
      "date": "2026-09-15"
    },
    {
      "id": "pool-DEL-First Officer",
      "severity": "warning",
      "subject": "DEL First Officer",
      "subject_type": "pool",
      "message": "Only 1 first officer reserve on call at DEL on 2026-09-15.",
      "date": "2026-09-15"
    },
    {
      "id": "pool-DEL-Senior Cabin Crew",
      "severity": "warning",
      "subject": "DEL Senior Cabin Crew",
      "subject_type": "pool",
      "message": "Only 1 senior cabin crew reserve on call at DEL on 2026-09-15.",
      "date": "2026-09-15"
    },
    {
      "id": "risk-C-1042",
      "severity": "info",
      "subject": "C-1042",
      "subject_type": "crew",
      "message": "Captain C-1042 carries a provided disruption-risk score of 0.78: short-rest pattern over last 14 days; two fatigue reports this month.",
      "date": "2026-09-15"
    },
    {
      "id": "risk-C-3940",
      "severity": "info",
      "subject": "C-3940",
      "subject_type": "crew",
      "message": "Captain C-3940 carries a provided disruption-risk score of 0.71: elevated sick-call likelihood: cluster pattern at base.",
      "date": "2026-09-15"
    }
  ],
  "evidence": [
    {
      "source": "RULE-DUTY-02",
      "fact": "max duty hours",
      "value": "60.0"
    },
    {
      "source": "RULE-DUTY-02",
      "fact": "window days",
      "value": "7"
    },
    {
      "source": "RULE-CERT-06",
      "fact": "alert horizon days",
      "value": "14"
    },
    {
      "source": "duty_clocks.json",
      "fact": "C-2087 duty hours to 2026-09-15",
      "value": "51.83"
    },
    {
      "source": "RULE-DUTY-02",
      "fact": "C-2087 headroom",
      "value": "8.17"
    },
    {
      "source": "certifications.json",
      "fact": "C-2087 licence expires",
      "value": "2026-09-18"
    },
    {
      "source": "certifications.json",
      "fact": "C-2091 medical_class1 expires",
      "value": "2026-09-23"
    },
    {
      "source": "certifications.json",
      "fact": "C-3116 dangerous_goods expires",
      "value": "2026-09-28"
    },
    {
      "source": "certifications.json",
      "fact": "C-5417 recurrent_training expires",
      "value": "2026-09-17"
    },
    {
      "source": "reserve_pool.json",
      "fact": "DEL Cabin Crew reserves on 2026-09-15",
      "value": "1"
    },
    {
      "source": "reserve_pool.json",
      "fact": "DEL Captain reserves on 2026-09-15",
      "value": "1"
    },
    {
      "source": "reserve_pool.json",
      "fact": "DEL First Officer reserves on 2026-09-15",
      "value": "1"
    },
    {
      "source": "reserve_pool.json",
      "fact": "DEL Senior Cabin Crew reserves on 2026-09-15",
      "value": "1"
    },
    {
      "source": "risk_signals.json",
      "fact": "C-1042 score",
      "value": "0.78"
    },
    {
      "source": "risk_signals.json",
      "fact": "C-3940 score",
      "value": "0.71"
    }
  ],
  "timing_ms": 0
};
