// GENERATED by backend/scripts/record_fixtures.py -- do not hand-edit.
// Recorded from the live deterministic engine, so offline mode shows real
// dataset facts rather than invented ones. Regenerate after engine changes.

import type { AdvisorResponse } from '../types/api';
import { mockImpactResponse } from './impact';
import { mockRecommendResponse, mockRelaxationResponse } from './recommend';
import { mockAlertsResponse } from './alerts';

export const mockReserveTable: AdvisorResponse = {
  "query": "Who is on reserve at BLR on 2026-09-15?",
  "intent": "recorded",
  "tier": 1,
  "answer_text": "12 reserve crew are on call at BLR on 2026-09-15.",
  "confidence": "high",
  "grounding": {
    "verified": true,
    "unverified_claims": []
  },
  "table": {
    "columns": [
      "Crew",
      "Name",
      "Rank",
      "Base",
      "On-call window",
      "Reachability"
    ],
    "rows": [
      [
        "C-1329",
        "P. Pillai",
        "Cabin Crew",
        "BLR",
        "04:00-16:00Z",
        "45 min"
      ],
      [
        "C-2111",
        "A. Gupta",
        "Senior Cabin Crew",
        "BLR",
        "04:00-16:00Z",
        "90 min"
      ],
      [
        "C-2248",
        "H. Reddy",
        "Cabin Crew",
        "BLR",
        "04:00-16:00Z",
        "60 min"
      ],
      [
        "C-3305",
        "V. Menon",
        "Captain",
        "BLR",
        "00:00-05:30Z",
        "45 min"
      ],
      [
        "C-3310",
        "D. Reddy",
        "Captain",
        "BLR",
        "06:00-18:00Z",
        "45 min"
      ],
      [
        "C-3311",
        "K. Rao",
        "First Officer",
        "BLR",
        "06:00-18:00Z",
        "45 min"
      ],
      [
        "C-3312",
        "P. Sharma",
        "First Officer",
        "BLR",
        "00:00-12:00Z",
        "60 min"
      ],
      [
        "C-3315",
        "M. Pillai",
        "Captain",
        "BLR",
        "03:00-15:00Z",
        "45 min"
      ],
      [
        "C-3316",
        "N. Verma",
        "First Officer",
        "BLR",
        "03:00-15:00Z",
        "45 min"
      ],
      [
        "C-3677",
        "M. Iyer",
        "Senior Cabin Crew",
        "BLR",
        "04:00-16:00Z",
        "45 min"
      ],
      [
        "C-4809",
        "M. Das",
        "Cabin Crew",
        "BLR",
        "00:00-12:00Z",
        "45 min"
      ],
      [
        "C-5418",
        "S. Das",
        "Cabin Crew",
        "BLR",
        "04:00-16:00Z",
        "45 min"
      ]
    ]
  },
  "notification": null,
  "evidence": [
    {
      "source": "reserve_pool.json",
      "fact": "C-1329 on-call 2026-09-15",
      "value": "04:00-16:00Z"
    },
    {
      "source": "reserve_pool.json",
      "fact": "C-2111 on-call 2026-09-15",
      "value": "04:00-16:00Z"
    },
    {
      "source": "reserve_pool.json",
      "fact": "C-2248 on-call 2026-09-15",
      "value": "04:00-16:00Z"
    },
    {
      "source": "reserve_pool.json",
      "fact": "C-3305 on-call 2026-09-15",
      "value": "00:00-05:30Z"
    },
    {
      "source": "reserve_pool.json",
      "fact": "C-3310 on-call 2026-09-15",
      "value": "06:00-18:00Z"
    },
    {
      "source": "reserve_pool.json",
      "fact": "C-3311 on-call 2026-09-15",
      "value": "06:00-18:00Z"
    },
    {
      "source": "reserve_pool.json",
      "fact": "C-3312 on-call 2026-09-15",
      "value": "00:00-12:00Z"
    },
    {
      "source": "reserve_pool.json",
      "fact": "C-3315 on-call 2026-09-15",
      "value": "03:00-15:00Z"
    },
    {
      "source": "reserve_pool.json",
      "fact": "C-3316 on-call 2026-09-15",
      "value": "03:00-15:00Z"
    },
    {
      "source": "reserve_pool.json",
      "fact": "C-3677 on-call 2026-09-15",
      "value": "04:00-16:00Z"
    },
    {
      "source": "reserve_pool.json",
      "fact": "C-4809 on-call 2026-09-15",
      "value": "00:00-12:00Z"
    },
    {
      "source": "reserve_pool.json",
      "fact": "C-5418 on-call 2026-09-15",
      "value": "04:00-16:00Z"
    }
  ],
  "timing_ms": 0
};

export const mockFollowUp: AdvisorResponse = {
  "query": "What is C-3310's reserve on-call window and reachability?",
  "intent": "recorded",
  "tier": 1,
  "answer_text": "Captain C-3310 (D. Reddy) is based at BLR, rated A320, reachable in 45 minutes.",
  "confidence": "high",
  "grounding": {
    "verified": true,
    "unverified_claims": []
  },
  "table": {
    "columns": [
      "Field",
      "Value"
    ],
    "rows": [
      [
        "Name",
        "D. Reddy"
      ],
      [
        "Rank",
        "Captain"
      ],
      [
        "Base",
        "BLR"
      ],
      [
        "Ratings",
        "A320"
      ],
      [
        "Seniority",
        9
      ],
      [
        "Reachability",
        "45 min"
      ],
      [
        "Status",
        "active"
      ],
      [
        "Reserve on-call",
        "06:00-18:00Z"
      ],
      [
        "Duty hours (7d)",
        0.0
      ],
      [
        "Block hours (28d)",
        9.34
      ],
      [
        "Disruption risk",
        0.17
      ],
      [
        "Risk drivers",
        "baseline"
      ]
    ]
  },
  "notification": null,
  "evidence": [
    {
      "source": "crew.json",
      "fact": "C-3310 rank",
      "value": "Captain"
    },
    {
      "source": "crew.json",
      "fact": "C-3310 base",
      "value": "BLR"
    },
    {
      "source": "crew.json",
      "fact": "C-3310 ratings",
      "value": "A320"
    },
    {
      "source": "crew.json",
      "fact": "C-3310 reachability",
      "value": "45 min"
    },
    {
      "source": "crew.json",
      "fact": "C-3310 status",
      "value": "active"
    },
    {
      "source": "reserve_pool.json",
      "fact": "C-3310 on-call window",
      "value": "06:00-18:00Z"
    },
    {
      "source": "duty_clocks.json",
      "fact": "C-3310 duty_hours_7d",
      "value": "0.0"
    },
    {
      "source": "duty_clocks.json",
      "fact": "C-3310 flight_hours_28d",
      "value": "9.34"
    },
    {
      "source": "risk_signals.json",
      "fact": "C-3310 disruption_risk_score",
      "value": "0.17"
    }
  ],
  "timing_ms": 0
};

export const mockCannotAnswer: AdvisorResponse = {
  "query": "What is the meaning of life?",
  "intent": "recorded",
  "tier": 1,
  "answer_text": "I could not map that to an operation I can answer reliably from this dataset. Try naming a crew id (C-1042), a pairing (P-2291), a flight (DX412) or a station and date.",
  "confidence": "cannot_answer",
  "grounding": {
    "verified": false,
    "unverified_claims": [
      "crew C-1042 does not appear in the evidence for this answer",
      "pairing P-2291 does not appear in the evidence for this answer",
      "flight DX412 does not appear in the evidence for this answer"
    ]
  },
  "notification": null,
  "evidence": [],
  "timing_ms": 0
};

export const mockSimulateResponse: AdvisorResponse = {
  "query": "If I move Captain C-2087 onto P-2291, does anyone breach a duty limit?",
  "intent": "recorded",
  "tier": 2,
  "answer_text": "No. Captain C-2087 cannot cover P-2291: RULE-DUTY-02: would exceed 60h/7d by 1h20m on 2026-09-15 (total 61.33h); RULE-DUTY-02: would exceed 60h/7d by 1h05m on 2026-09-16 (total 61.08h).",
  "confidence": "high",
  "grounding": {
    "verified": true,
    "unverified_claims": []
  },
  "table": {
    "columns": [
      "Rule",
      "Status",
      "Actual",
      "Limit",
      "Detail"
    ],
    "rows": [
      [
        "RULE-FDP-01",
        "PASS",
        10.75,
        12.5,
        "2026-09-16: FDP 10.75h over 3 sectors, limit 12.5h"
      ],
      [
        "RULE-DUTY-02",
        "FAIL",
        61.33,
        60.0,
        "would exceed 60h/7d by 1h20m on 2026-09-15 (total 61.33h)"
      ],
      [
        "RULE-FLT-03",
        "PASS",
        37.5,
        100.0,
        "2026-09-16: 37.5h block in 28 calendar days, limit 100.0h"
      ],
      [
        "RULE-REST-04",
        "PASS",
        12.5,
        12.0,
        "12.5h rest between the new assignment (2026-09-15) and the new assignment (2026-09-16), minimum 12h"
      ],
      [
        "RULE-QUAL-05",
        "PASS",
        "A320",
        "A320",
        "rated for A320"
      ],
      [
        "RULE-CERT-06",
        "PASS",
        "2026-09-18",
        "2026-09-16",
        "all certifications valid on 2026-09-16; earliest expiry licence 2026-09-18 (2 days)"
      ],
      [
        "RULE-BASE-07",
        "PASS",
        "BLR",
        "BLR",
        "based at BLR, no positioning required"
      ]
    ]
  },
  "before_after": [
    {
      "field": "Duty hours (7 calendar days)",
      "before": "40.83h",
      "after": "61.08h",
      "delta": "+20.25h",
      "legal": false
    },
    {
      "field": "Block hours (28 calendar days)",
      "before": "23.5h",
      "after": "37.5h",
      "delta": "+14.0h",
      "legal": true
    },
    {
      "field": "Overall legality",
      "before": "available",
      "after": "ILLEGAL",
      "delta": "RULE-DUTY-02: would exceed 60h/7d by 1h20m on 2026-09-15 (total 61.33h); RULE-DUTY-02: would exceed 60h/7d by 1h05m on 2026-09-16 (total 61.08h)",
      "legal": false
    }
  ],
  "notification": null,
  "evidence": [
    {
      "source": "crew.json",
      "fact": "C-2087 rank",
      "value": "Captain"
    },
    {
      "source": "crew.json",
      "fact": "C-2087 base",
      "value": "BLR"
    },
    {
      "source": "crew.json",
      "fact": "C-2087 ratings",
      "value": "A320"
    },
    {
      "source": "RULE-FDP-01",
      "fact": "PASS",
      "value": "2026-09-16: FDP 10.75h over 3 sectors, limit 12.5h"
    },
    {
      "source": "RULE-DUTY-02",
      "fact": "FAIL",
      "value": "would exceed 60h/7d by 1h20m on 2026-09-15 (total 61.33h)"
    },
    {
      "source": "RULE-FLT-03",
      "fact": "PASS",
      "value": "2026-09-16: 37.5h block in 28 calendar days, limit 100.0h"
    },
    {
      "source": "RULE-REST-04",
      "fact": "PASS",
      "value": "12.5h rest between the new assignment (2026-09-15) and the new assignment (2026-09-16), minimum 12h"
    },
    {
      "source": "RULE-QUAL-05",
      "fact": "PASS",
      "value": "rated for A320"
    },
    {
      "source": "RULE-CERT-06",
      "fact": "PASS",
      "value": "all certifications valid on 2026-09-16; earliest expiry licence 2026-09-18 (2 days)"
    },
    {
      "source": "RULE-BASE-07",
      "fact": "PASS",
      "value": "based at BLR, no positioning required"
    },
    {
      "source": "costs.json",
      "fact": "assignment cost",
      "value": "24000"
    }
  ],
  "timing_ms": 0
};


/** Routes a typed question to the closest recorded fixture. */
export function resolveMockChat(question: string): AdvisorResponse {
  const q = question.toLowerCase();
  if (/(sick|out for|unavailable|what should i do|options|recommend)/.test(q)) {
    return { ...mockRecommendResponse, query: question };
  }
  if (/(delay|delayed|fdp)/.test(q)) {
    return { ...mockRelaxationResponse, query: question };
  }
  if (/(uncrewed|uncovered|impact|affected|closed|closure)/.test(q)) {
    return { ...mockImpactResponse, query: question };
  }
  if (/(worry|risky|alert|briefing|watch)/.test(q)) {
    return { ...mockAlertsResponse, query: question };
  }
  if (/reserve/.test(q)) return { ...mockReserveTable, query: question };
  if (/(window|reachab|base|rating|profile)/.test(q)) {
    return { ...mockFollowUp, query: question };
  }
  return { ...mockCannotAnswer, query: question };
}
