// GENERATED by backend/scripts/record_fixtures.py -- do not hand-edit.
// Recorded from the live deterministic engine, so offline mode shows real
// dataset facts rather than invented ones. Regenerate after engine changes.

import type { AdvisorResponse } from '../types/api';

export const mockImpactResponse: AdvisorResponse = {
  "query": "Captain C-1042 called in sick on 15 Sep. Which flights are uncrewed?",
  "intent": "recorded",
  "tier": 2,
  "answer_text": "C-1042 sick. 6 legs are uncovered (DX412, DX413, DX588, DX589, DX590, DX591), affecting 486 passengers across 1 pairing(s).",
  "confidence": "high",
  "grounding": {
    "verified": true,
    "unverified_claims": []
  },
  "table": {
    "columns": [
      "Flight",
      "Date",
      "Sector",
      "Dep",
      "Seats",
      "Pairing"
    ],
    "rows": [
      [
        "DX412",
        "2026-09-15",
        "BLR-BOM",
        "07:00Z",
        162,
        "P-2291"
      ],
      [
        "DX413",
        "2026-09-15",
        "BOM-BLR",
        "09:30Z",
        162,
        "P-2291"
      ],
      [
        "DX588",
        "2026-09-15",
        "BLR-DEL",
        "12:15Z",
        162,
        "P-2291"
      ],
      [
        "DX589",
        "2026-09-16",
        "DEL-BLR",
        "05:00Z",
        162,
        "P-2291"
      ],
      [
        "DX590",
        "2026-09-16",
        "BLR-CCU",
        "08:30Z",
        162,
        "P-2291"
      ],
      [
        "DX591",
        "2026-09-16",
        "CCU-BLR",
        "11:45Z",
        162,
        "P-2291"
      ]
    ]
  },
  "impact": {
    "trigger": "C-1042 sick",
    "uncrewed_flights": [
      "DX412-2026-09-15",
      "DX413-2026-09-15",
      "DX588-2026-09-15",
      "DX589-2026-09-16",
      "DX590-2026-09-16",
      "DX591-2026-09-16"
    ],
    "immediate_flights": [
      "DX412-2026-09-15",
      "DX413-2026-09-15",
      "DX588-2026-09-15"
    ],
    "at_risk_flights": [
      "DX589-2026-09-16",
      "DX590-2026-09-16",
      "DX591-2026-09-16"
    ],
    "pairing_broken": [
      "P-2291"
    ],
    "downstream_risks": [
      {
        "crew_id": "C-1694",
        "rule": "COVERAGE",
        "detail": "rostered on P-2291 which cannot operate until the vacancy is filled"
      },
      {
        "crew_id": "C-3005",
        "rule": "COVERAGE",
        "detail": "rostered on P-2291 which cannot operate until the vacancy is filled"
      },
      {
        "crew_id": "C-4395",
        "rule": "COVERAGE",
        "detail": "rostered on P-2291 which cannot operate until the vacancy is filled"
      },
      {
        "crew_id": "C-4273",
        "rule": "COVERAGE",
        "detail": "rostered on P-2291 which cannot operate until the vacancy is filled"
      },
      {
        "crew_id": "C-1873",
        "rule": "COVERAGE",
        "detail": "rostered on P-2291 which cannot operate until the vacancy is filled"
      }
    ],
    "passengers_affected": 486,
    "graph": {
      "nodes": [
        {
          "id": "C-1042",
          "label": "Captain C-1042",
          "type": "crew",
          "status": "broken"
        },
        {
          "id": "P-2291",
          "label": "P-2291",
          "type": "pairing",
          "status": "broken"
        },
        {
          "id": "DX412-2026-09-15",
          "label": "DX412",
          "type": "flight",
          "status": "broken"
        },
        {
          "id": "DX413-2026-09-15",
          "label": "DX413",
          "type": "flight",
          "status": "broken"
        },
        {
          "id": "DX588-2026-09-15",
          "label": "DX588",
          "type": "flight",
          "status": "broken"
        },
        {
          "id": "DX589-2026-09-16",
          "label": "DX589",
          "type": "flight",
          "status": "at_risk"
        },
        {
          "id": "DX590-2026-09-16",
          "label": "DX590",
          "type": "flight",
          "status": "at_risk"
        },
        {
          "id": "DX591-2026-09-16",
          "label": "DX591",
          "type": "flight",
          "status": "at_risk"
        }
      ],
      "edges": [
        {
          "from": "C-1042",
          "to": "P-2291"
        },
        {
          "from": "P-2291",
          "to": "DX412-2026-09-15"
        },
        {
          "from": "P-2291",
          "to": "DX413-2026-09-15"
        },
        {
          "from": "P-2291",
          "to": "DX588-2026-09-15"
        },
        {
          "from": "P-2291",
          "to": "DX589-2026-09-16"
        },
        {
          "from": "P-2291",
          "to": "DX590-2026-09-16"
        },
        {
          "from": "P-2291",
          "to": "DX591-2026-09-16"
        }
      ]
    }
  },
  "notification": null,
  "evidence": [
    {
      "source": "computed",
      "fact": "trigger",
      "value": "C-1042 sick"
    },
    {
      "source": "rosters.json",
      "fact": "pairing affected",
      "value": "P-2291"
    },
    {
      "source": "flights.json",
      "fact": "uncovered leg",
      "value": "DX412 on 2026-09-15"
    },
    {
      "source": "flights.json",
      "fact": "uncovered leg",
      "value": "DX413 on 2026-09-15"
    },
    {
      "source": "flights.json",
      "fact": "uncovered leg",
      "value": "DX588 on 2026-09-15"
    },
    {
      "source": "flights.json",
      "fact": "uncovered leg",
      "value": "DX589 on 2026-09-16"
    },
    {
      "source": "flights.json",
      "fact": "uncovered leg",
      "value": "DX590 on 2026-09-16"
    },
    {
      "source": "flights.json",
      "fact": "uncovered leg",
      "value": "DX591 on 2026-09-16"
    },
    {
      "source": "flights.json",
      "fact": "passengers affected",
      "value": "486"
    },
    {
      "source": "computed",
      "fact": "downstream risk C-1694",
      "value": "rostered on P-2291 which cannot operate until the vacancy is filled"
    },
    {
      "source": "computed",
      "fact": "downstream risk C-3005",
      "value": "rostered on P-2291 which cannot operate until the vacancy is filled"
    },
    {
      "source": "computed",
      "fact": "downstream risk C-4395",
      "value": "rostered on P-2291 which cannot operate until the vacancy is filled"
    },
    {
      "source": "computed",
      "fact": "downstream risk C-4273",
      "value": "rostered on P-2291 which cannot operate until the vacancy is filled"
    },
    {
      "source": "computed",
      "fact": "downstream risk C-1873",
      "value": "rostered on P-2291 which cannot operate until the vacancy is filled"
    }
  ],
  "timing_ms": 0
};
