// GENERATED by backend/scripts/record_fixtures.py -- do not hand-edit.
// Recorded from the live deterministic engine, so offline mode shows real
// dataset facts rather than invented ones. Regenerate after engine changes.

import type { McpInfo } from '../types/api';

export const mockMcpInfo: McpInfo = {
  "server_name": "crew-ops",
  "transport": "stdio",
  "command": "<repo>/backend/.venv/Scripts/python.exe",
  "args": [
    "<repo>/backend/mcp_server/index.py"
  ],
  "config_json": "{\n  \"mcpServers\": {\n    \"crew-ops\": {\n      \"command\": \"<repo>/backend/.venv/Scripts/python.exe\",\n      \"args\": [\n        \"<repo>/backend/mcp_server/index.py\"\n      ]\n    }\n  }\n}",
  "config_path": {
    "windows": "%APPDATA%\\Claude\\claude_desktop_config.json",
    "macos": "~/Library/Application Support/Claude/claude_desktop_config.json"
  },
  "tools": [
    {
      "name": "get_crew_profile",
      "tier": 1,
      "description": "Full profile for one crew member: rank, base, ratings, reachability, reserve window, duty clocks, risk score, pairings."
    },
    {
      "name": "search_crew",
      "tier": 1,
      "description": "Find crew by rank, base and/or aircraft rating."
    },
    {
      "name": "get_reserves",
      "tier": 1,
      "description": "Reserve crew on call for a date, optionally filtered by base, rank, and whether their window covers a given callout time."
    },
    {
      "name": "get_duty_clock",
      "tier": 1,
      "description": "Duty hours in the 7 calendar days and block hours in the 28 calendar days ending on a date, with headroom under each rule."
    },
    {
      "name": "find_crew_near_duty_limit",
      "tier": 1,
      "description": "Crew at or above a duty-hour threshold for the 7 days ending on a date."
    },
    {
      "name": "search_flights",
      "tier": 1,
      "description": "Query the schedule by date, departure/arrival station, flight number or tail."
    },
    {
      "name": "get_expiring_certifications",
      "tier": 1,
      "description": "Certifications expiring within N days of a date."
    },
    {
      "name": "get_pairing",
      "tier": 1,
      "description": "A pairing's crew, roles, days and legs."
    },
    {
      "name": "analyse_disruption",
      "tier": 2,
      "description": "Tier 2/3. Apply one or more disruptions to a copy of the operation and report what breaks: uncovered legs, broken pairings, downstream rule breaches, passengers affected. For a STATION CLOSURE it returns the complete plan -- per-leg minimum delay to reopen, crew FDP after that delay against the limit, and costed options (delay / re-crew the tail / cancel) -- so no further tool call is needed. Never mutates the real roster."
    },
    {
      "name": "check_assignment_legality",
      "tier": 2,
      "description": "Tier 2. Would assigning this crew member to this pairing be legal? Returns a rule-by-rule verdict with actuals, limits and margins, plus before/after duty position."
    },
    {
      "name": "get_cancellation_impact",
      "tier": 2,
      "description": "Passengers affected and direct cost of cancelling specific legs."
    },
    {
      "name": "recommend_recovery",
      "tier": 3,
      "description": "Tier 3. Ranked, rule-checked recovery options for a vacancy, including multi-step swap chains, costs, coverage, resilience and why each rejected candidate was rejected."
    },
    {
      "name": "get_earliest_report",
      "tier": 1,
      "description": "Earliest legal next report after a release time (RULE-REST-04)."
    },
    {
      "name": "get_alerts",
      "tier": 2,
      "description": "Proactive operational signals for a date: duty headroom, certification expiry, reserve depth, thin cover, provided risk scores."
    },
    {
      "name": "draft_crew_notification",
      "tier": 3,
      "description": "Draft the callout message for a crew member on a pairing."
    }
  ]
};
