// GENERATED by backend/scripts/record_fixtures.py -- do not hand-edit.
// Recorded from the live deterministic engine, so offline mode shows real
// dataset facts rather than invented ones. Regenerate after engine changes.

import type { AdvisorResponse } from '../types/api';

export const mockRecommendResponse: AdvisorResponse = {
  "query": "Captain C-1042 is out for P-2291. What should I do?",
  "intent": "recorded",
  "tier": 3,
  "answer_text": "5 legal option(s) cover P-2291. Recommended: Assign Captain C-3310 (reserve callout) at INR 18,500, covering all 6 flights.",
  "confidence": "high",
  "grounding": {
    "verified": true,
    "unverified_claims": []
  },
  "options": [
    {
      "rank": 1,
      "action": "Assign Captain C-3310 (reserve callout)",
      "legal": true,
      "rules_checked": [
        "RULE-FDP-01",
        "RULE-DUTY-02",
        "RULE-FLT-03",
        "RULE-REST-04",
        "RULE-QUAL-05",
        "RULE-CERT-06",
        "RULE-BASE-07"
      ],
      "rule_checks": [
        {
          "rule_id": "RULE-FDP-01",
          "status": "PASS",
          "actual": 10.75,
          "limit": 12.5,
          "margin": 1.75,
          "detail": "2026-09-16: FDP 10.75h over 3 sectors, limit 12.5h"
        },
        {
          "rule_id": "RULE-DUTY-02",
          "status": "PASS",
          "actual": 20.25,
          "limit": 60.0,
          "margin": 39.75,
          "detail": "2026-09-16: 20.25h duty in 7 calendar days, limit 60.0h"
        },
        {
          "rule_id": "RULE-FLT-03",
          "status": "PASS",
          "actual": 23.34,
          "limit": 100.0,
          "margin": 76.66,
          "detail": "2026-09-16: 23.34h block in 28 calendar days, limit 100.0h"
        },
        {
          "rule_id": "RULE-REST-04",
          "status": "PASS",
          "actual": 12.5,
          "limit": 12.0,
          "margin": 0.5,
          "detail": "12.5h rest between the new assignment (2026-09-15) and the new assignment (2026-09-16), minimum 12h"
        },
        {
          "rule_id": "RULE-QUAL-05",
          "status": "PASS",
          "actual": "A320",
          "limit": "A320",
          "margin": null,
          "detail": "rated for A320"
        },
        {
          "rule_id": "RULE-CERT-06",
          "status": "PASS",
          "actual": "2027-06-15",
          "limit": "2026-09-16",
          "margin": 272.0,
          "detail": "all certifications valid on 2026-09-16; earliest expiry recurrent_training 2027-06-15 (272 days)"
        },
        {
          "rule_id": "RULE-BASE-07",
          "status": "PASS",
          "actual": "BLR",
          "limit": "BLR",
          "margin": null,
          "detail": "based at BLR, no positioning required"
        }
      ],
      "cost_inr": 18500,
      "cost_breakdown": [
        {
          "label": "Reserve callout",
          "amount_inr": 18500
        }
      ],
      "coverage": "all 6 flights",
      "covered_flight_ids": [
        "DX412-2026-09-15",
        "DX413-2026-09-15",
        "DX588-2026-09-15",
        "DX589-2026-09-16",
        "DX590-2026-09-16",
        "DX591-2026-09-16"
      ],
      "uncovered_flight_ids": [],
      "delay_minutes": 0,
      "resilience_score": 0.8,
      "resilience_note": "4 of 5 legal captains remain; 4 upcoming pairing(s) would be left with one or no cover: P-2225, P-2226, P-2232 (+1 more)",
      "chain": [],
      "reasoning": "BLR-based; A320-rated; on call 06:00-18:00Z; reachable in 45 min; 50.5h duty headroom remaining."
    },
    {
      "rank": 2,
      "action": "Assign Captain C-1526 (day-off callout)",
      "legal": true,
      "rules_checked": [
        "RULE-FDP-01",
        "RULE-DUTY-02",
        "RULE-FLT-03",
        "RULE-REST-04",
        "RULE-QUAL-05",
        "RULE-CERT-06",
        "RULE-BASE-07"
      ],
      "rule_checks": [
        {
          "rule_id": "RULE-FDP-01",
          "status": "PASS",
          "actual": 10.75,
          "limit": 12.5,
          "margin": 1.75,
          "detail": "2026-09-16: FDP 10.75h over 3 sectors, limit 12.5h"
        },
        {
          "rule_id": "RULE-DUTY-02",
          "status": "PASS",
          "actual": 40.43,
          "limit": 60.0,
          "margin": 19.57,
          "detail": "2026-09-16: 40.43h duty in 7 calendar days, limit 60.0h"
        },
        {
          "rule_id": "RULE-FLT-03",
          "status": "PASS",
          "actual": 76.32,
          "limit": 100.0,
          "margin": 23.68,
          "detail": "2026-09-16: 76.32h block in 28 calendar days, limit 100.0h"
        },
        {
          "rule_id": "RULE-REST-04",
          "status": "PASS",
          "actual": 12.5,
          "limit": 12.0,
          "margin": 0.5,
          "detail": "12.5h rest between the new assignment (2026-09-15) and the new assignment (2026-09-16), minimum 12h"
        },
        {
          "rule_id": "RULE-QUAL-05",
          "status": "PASS",
          "actual": "A320",
          "limit": "A320",
          "margin": null,
          "detail": "rated for A320"
        },
        {
          "rule_id": "RULE-CERT-06",
          "status": "PASS",
          "actual": "2027-06-13",
          "limit": "2026-09-16",
          "margin": 270.0,
          "detail": "all certifications valid on 2026-09-16; earliest expiry recurrent_training 2027-06-13 (270 days)"
        },
        {
          "rule_id": "RULE-BASE-07",
          "status": "PASS",
          "actual": "BLR",
          "limit": "BLR",
          "margin": null,
          "detail": "based at BLR, no positioning required"
        }
      ],
      "cost_inr": 24000,
      "cost_breakdown": [
        {
          "label": "Day-off callout",
          "amount_inr": 24000
        }
      ],
      "coverage": "all 6 flights",
      "covered_flight_ids": [
        "DX412-2026-09-15",
        "DX413-2026-09-15",
        "DX588-2026-09-15",
        "DX589-2026-09-16",
        "DX590-2026-09-16",
        "DX591-2026-09-16"
      ],
      "uncovered_flight_ids": [],
      "delay_minutes": 0,
      "resilience_score": 0.8,
      "resilience_note": "4 of 5 legal captains remain; 4 upcoming pairing(s) would be left with one or no cover: P-2225, P-2226, P-2232 (+1 more)",
      "chain": [],
      "reasoning": "BLR-based; A320-rated; not rostered on these dates; reachable in 90 min; 30.32h duty headroom remaining."
    },
    {
      "rank": 3,
      "action": "Assign Captain C-3983 (day-off callout)",
      "legal": true,
      "rules_checked": [
        "RULE-FDP-01",
        "RULE-DUTY-02",
        "RULE-FLT-03",
        "RULE-REST-04",
        "RULE-QUAL-05",
        "RULE-CERT-06",
        "RULE-BASE-07"
      ],
      "rule_checks": [
        {
          "rule_id": "RULE-FDP-01",
          "status": "PASS",
          "actual": 10.75,
          "limit": 12.5,
          "margin": 1.75,
          "detail": "2026-09-16: FDP 10.75h over 3 sectors, limit 12.5h"
        },
        {
          "rule_id": "RULE-DUTY-02",
          "status": "PASS",
          "actual": 49.86,
          "limit": 60.0,
          "margin": 10.14,
          "detail": "2026-09-16: 49.86h duty in 7 calendar days, limit 60.0h"
        },
        {
          "rule_id": "RULE-FLT-03",
          "status": "PASS",
          "actual": 75.66,
          "limit": 100.0,
          "margin": 24.34,
          "detail": "2026-09-16: 75.66h block in 28 calendar days, limit 100.0h"
        },
        {
          "rule_id": "RULE-REST-04",
          "status": "PASS",
          "actual": 12.5,
          "limit": 12.0,
          "margin": 0.5,
          "detail": "12.5h rest between the new assignment (2026-09-15) and the new assignment (2026-09-16), minimum 12h"
        },
        {
          "rule_id": "RULE-QUAL-05",
          "status": "PASS",
          "actual": "A320",
          "limit": "A320",
          "margin": null,
          "detail": "rated for A320"
        },
        {
          "rule_id": "RULE-CERT-06",
          "status": "PASS",
          "actual": "2027-02-22",
          "limit": "2026-09-16",
          "margin": 159.0,
          "detail": "all certifications valid on 2026-09-16; earliest expiry dangerous_goods 2027-02-22 (159 days)"
        },
        {
          "rule_id": "RULE-BASE-07",
          "status": "PASS",
          "actual": "BLR",
          "limit": "BLR",
          "margin": null,
          "detail": "based at BLR, no positioning required"
        }
      ],
      "cost_inr": 24000,
      "cost_breakdown": [
        {
          "label": "Day-off callout",
          "amount_inr": 24000
        }
      ],
      "coverage": "all 6 flights",
      "covered_flight_ids": [
        "DX412-2026-09-15",
        "DX413-2026-09-15",
        "DX588-2026-09-15",
        "DX589-2026-09-16",
        "DX590-2026-09-16",
        "DX591-2026-09-16"
      ],
      "uncovered_flight_ids": [],
      "delay_minutes": 0,
      "resilience_score": 0.8,
      "resilience_note": "4 of 5 legal captains remain; 4 upcoming pairing(s) would be left with one or no cover: P-2225, P-2226, P-2232 (+1 more)",
      "chain": [],
      "reasoning": "BLR-based; A320-rated; not rostered on these dates; reachable in 45 min; 20.89h duty headroom remaining."
    },
    {
      "rank": 4,
      "action": "Assign Captain C-5566 (day-off callout)",
      "legal": true,
      "rules_checked": [
        "RULE-FDP-01",
        "RULE-DUTY-02",
        "RULE-FLT-03",
        "RULE-REST-04",
        "RULE-QUAL-05",
        "RULE-CERT-06",
        "RULE-BASE-07"
      ],
      "rule_checks": [
        {
          "rule_id": "RULE-FDP-01",
          "status": "PASS",
          "actual": 10.75,
          "limit": 12.5,
          "margin": 1.75,
          "detail": "2026-09-16: FDP 10.75h over 3 sectors, limit 12.5h"
        },
        {
          "rule_id": "RULE-DUTY-02",
          "status": "PASS",
          "actual": 29.91,
          "limit": 60.0,
          "margin": 30.09,
          "detail": "2026-09-16: 29.91h duty in 7 calendar days, limit 60.0h"
        },
        {
          "rule_id": "RULE-FLT-03",
          "status": "PASS",
          "actual": 67.03,
          "limit": 100.0,
          "margin": 32.97,
          "detail": "2026-09-16: 67.03h block in 28 calendar days, limit 100.0h"
        },
        {
          "rule_id": "RULE-REST-04",
          "status": "PASS",
          "actual": 12.5,
          "limit": 12.0,
          "margin": 0.5,
          "detail": "12.5h rest between the new assignment (2026-09-15) and the new assignment (2026-09-16), minimum 12h"
        },
        {
          "rule_id": "RULE-QUAL-05",
          "status": "PASS",
          "actual": "A320",
          "limit": "A320",
          "margin": null,
          "detail": "rated for A320"
        },
        {
          "rule_id": "RULE-CERT-06",
          "status": "PASS",
          "actual": "2027-08-01",
          "limit": "2026-09-16",
          "margin": 319.0,
          "detail": "all certifications valid on 2026-09-16; earliest expiry recurrent_training 2027-08-01 (319 days)"
        },
        {
          "rule_id": "RULE-BASE-07",
          "status": "PASS",
          "actual": "BLR",
          "limit": "BLR",
          "margin": null,
          "detail": "based at BLR, no positioning required"
        }
      ],
      "cost_inr": 24000,
      "cost_breakdown": [
        {
          "label": "Day-off callout",
          "amount_inr": 24000
        }
      ],
      "coverage": "all 6 flights",
      "covered_flight_ids": [
        "DX412-2026-09-15",
        "DX413-2026-09-15",
        "DX588-2026-09-15",
        "DX589-2026-09-16",
        "DX590-2026-09-16",
        "DX591-2026-09-16"
      ],
      "uncovered_flight_ids": [],
      "delay_minutes": 0,
      "resilience_score": 0.8,
      "resilience_note": "4 of 5 legal captains remain; 4 upcoming pairing(s) would be left with one or no cover: P-2225, P-2226, P-2232 (+1 more)",
      "chain": [],
      "reasoning": "BLR-based; A320-rated; not rostered on these dates; reachable in 60 min; 40.84h duty headroom remaining."
    },
    {
      "rank": 5,
      "action": "Assign Captain C-2210 (reserve callout + deadhead from DEL (first departure delayed ~3.0h))",
      "legal": true,
      "rules_checked": [
        "RULE-FDP-01",
        "RULE-DUTY-02",
        "RULE-FLT-03",
        "RULE-REST-04",
        "RULE-QUAL-05",
        "RULE-CERT-06",
        "RULE-BASE-07"
      ],
      "rule_checks": [
        {
          "rule_id": "RULE-FDP-01",
          "status": "PASS",
          "actual": 10.75,
          "limit": 12.5,
          "margin": 1.75,
          "detail": "2026-09-16: FDP 10.75h over 3 sectors, limit 12.5h"
        },
        {
          "rule_id": "RULE-DUTY-02",
          "status": "PASS",
          "actual": 35.31,
          "limit": 60.0,
          "margin": 24.69,
          "detail": "2026-09-16: 35.31h duty in 7 calendar days, limit 60.0h"
        },
        {
          "rule_id": "RULE-FLT-03",
          "status": "PASS",
          "actual": 50.15,
          "limit": 100.0,
          "margin": 49.85,
          "detail": "2026-09-16: 50.15h block in 28 calendar days, limit 100.0h"
        },
        {
          "rule_id": "RULE-REST-04",
          "status": "PASS",
          "actual": 12.5,
          "limit": 12.0,
          "margin": 0.5,
          "detail": "12.5h rest between the new assignment (2026-09-15) and the new assignment (2026-09-16), minimum 12h"
        },
        {
          "rule_id": "RULE-QUAL-05",
          "status": "PASS",
          "actual": "A320",
          "limit": "A320",
          "margin": null,
          "detail": "rated for A320"
        },
        {
          "rule_id": "RULE-CERT-06",
          "status": "PASS",
          "actual": "2027-01-12",
          "limit": "2026-09-16",
          "margin": 118.0,
          "detail": "all certifications valid on 2026-09-16; earliest expiry recurrent_training 2027-01-12 (118 days)"
        },
        {
          "rule_id": "RULE-BASE-07",
          "status": "PASS",
          "actual": "DEL",
          "limit": "BLR",
          "margin": null,
          "detail": "deadhead DEL->BLR on DX402 (arrives 08:45Z); first departure delayed 3.0h"
        }
      ],
      "cost_inr": 41200,
      "cost_breakdown": [
        {
          "label": "Reserve callout",
          "amount_inr": 18500
        },
        {
          "label": "Deadhead positioning from DEL",
          "amount_inr": 6500
        },
        {
          "label": "Delay cost (3.0h x 5,400/h)",
          "amount_inr": 16200
        }
      ],
      "coverage": "all 6 flights",
      "covered_flight_ids": [
        "DX412-2026-09-15",
        "DX413-2026-09-15",
        "DX588-2026-09-15",
        "DX589-2026-09-16",
        "DX590-2026-09-16",
        "DX591-2026-09-16"
      ],
      "uncovered_flight_ids": [],
      "delay_minutes": 180,
      "resilience_score": 0.8,
      "resilience_note": "4 of 5 legal captains remain; 4 upcoming pairing(s) would be left with one or no cover: P-2225, P-2226, P-2232 (+1 more)",
      "chain": [],
      "reasoning": "DEL-based; A320-rated; on call 03:00-15:00Z; reachable in 60 min; 35.44h duty headroom remaining; deadhead DEL->BLR on DX402 (arrives 08:45Z); first departure delayed 3.0h."
    },
    {
      "rank": 6,
      "action": "Cancel all 6 flights of the pairing",
      "legal": true,
      "rules_checked": [],
      "rule_checks": [],
      "cost_inr": 1500000,
      "cost_breakdown": [
        {
          "label": "Cancellation (6 legs x 250,000)",
          "amount_inr": 1500000
        }
      ],
      "coverage": "no flights covered",
      "covered_flight_ids": [],
      "uncovered_flight_ids": [
        "DX412-2026-09-15",
        "DX413-2026-09-15",
        "DX588-2026-09-15",
        "DX589-2026-09-16",
        "DX590-2026-09-16",
        "DX591-2026-09-16"
      ],
      "delay_minutes": 0,
      "resilience_score": 1.0,
      "resilience_note": "consumes no crew capacity",
      "chain": [],
      "reasoning": "Baseline fallback. 972 seats to reaccommodate; shown so every cheaper option can be read against it."
    }
  ],
  "evidence": [
    {
      "source": "computed",
      "fact": "candidates evaluated",
      "value": "24"
    },
    {
      "source": "computed",
      "fact": "legal options",
      "value": "5"
    },
    {
      "source": "computed",
      "fact": "option 1",
      "value": "Assign Captain C-3310 (reserve callout)"
    },
    {
      "source": "costs.json",
      "fact": "option 1 cost",
      "value": "18500"
    },
    {
      "source": "computed",
      "fact": "option 2",
      "value": "Assign Captain C-1526 (day-off callout)"
    },
    {
      "source": "costs.json",
      "fact": "option 2 cost",
      "value": "24000"
    },
    {
      "source": "computed",
      "fact": "option 3",
      "value": "Assign Captain C-3983 (day-off callout)"
    },
    {
      "source": "costs.json",
      "fact": "option 3 cost",
      "value": "24000"
    },
    {
      "source": "computed",
      "fact": "option 4",
      "value": "Assign Captain C-5566 (day-off callout)"
    },
    {
      "source": "costs.json",
      "fact": "option 4 cost",
      "value": "24000"
    },
    {
      "source": "computed",
      "fact": "option 5",
      "value": "Assign Captain C-2210 (reserve callout + deadhead from DEL (first departure delayed ~3.0h))"
    },
    {
      "source": "costs.json",
      "fact": "option 5 cost",
      "value": "41200"
    },
    {
      "source": "computed",
      "fact": "option 6",
      "value": "Cancel all 6 flights of the pairing"
    },
    {
      "source": "costs.json",
      "fact": "option 6 cost",
      "value": "1500000"
    },
    {
      "source": "computed",
      "fact": "excluded C-1017",
      "value": "RULE-REST-04: only 11.0h rest after the new assignment on 2026-09-16, minimum 12h; RULE-REST-04: double-booked: P-2217 on 2026-09-16 overlaps the new assignment on 2026-09-16"
    },
    {
      "source": "computed",
      "fact": "excluded C-1443",
      "value": "RULE-REST-04: double-booked: P-2216 on 2026-09-15 overlaps the new assignment on 2026-09-15"
    },
    {
      "source": "computed",
      "fact": "excluded C-1600",
      "value": "RULE-REST-04: double-booked: P-2223 on 2026-09-15 overlaps the new assignment on 2026-09-15; RULE-QUAL-05: no A320 rating (holds ATR72)"
    },
    {
      "source": "computed",
      "fact": "excluded C-1671",
      "value": "RULE-QUAL-05: no A320 rating (holds ATR72)"
    },
    {
      "source": "computed",
      "fact": "excluded C-1938",
      "value": "RULE-REST-04: double-booked: P-2209 on 2026-09-15 overlaps the new assignment on 2026-09-15"
    },
    {
      "source": "computed",
      "fact": "excluded C-2087",
      "value": "RULE-DUTY-02: would exceed 60h/7d by 1h20m on 2026-09-15 (total 61.33h); RULE-DUTY-02: would exceed 60h/7d by 1h05m on 2026-09-16 (total 61.08h)"
    },
    {
      "source": "computed",
      "fact": "excluded C-2091",
      "value": "RULE-QUAL-05: no A320 rating (holds ATR72)"
    },
    {
      "source": "computed",
      "fact": "excluded C-2143",
      "value": "RULE-REST-04: only 11.25h rest after the new assignment on 2026-09-17, minimum 12h"
    },
    {
      "source": "computed",
      "fact": "excluded C-2221",
      "value": "RULE-QUAL-05: no A320 rating (holds ATR72)"
    },
    {
      "source": "computed",
      "fact": "excluded C-3187",
      "value": "RULE-REST-04: only 10.0h rest after the new assignment on 2026-09-16, minimum 12h; RULE-REST-04: double-booked: P-2203 on 2026-09-16 overlaps the new assignment on 2026-09-16"
    },
    {
      "source": "computed",
      "fact": "excluded C-3231",
      "value": "RULE-REST-04: only 11.5h rest after the new assignment on 2026-09-16, minimum 12h; RULE-REST-04: double-booked: P-2224 on 2026-09-16 overlaps the new assignment on 2026-09-16; RULE-QUAL-05: no A320 rating (holds ATR72)"
    },
    {
      "source": "computed",
      "fact": "excluded C-3305",
      "value": "RULE-DUTY-02: would exceed 60h/7d by 8h15m on 2026-09-16 (total 68.25h); RULE-BASE-07: reserve on-call window 00:00-05:30Z does not cover required report 06:00Z"
    },
    {
      "source": "computed",
      "fact": "excluded C-3315",
      "value": "RULE-QUAL-05: no A320 rating (holds ATR72)"
    },
    {
      "source": "computed",
      "fact": "excluded C-3721",
      "value": "RULE-REST-04: double-booked: P-2230 on 2026-09-15 overlaps the new assignment on 2026-09-15; RULE-QUAL-05: no A320 rating (holds ATR72)"
    },
    {
      "source": "computed",
      "fact": "excluded C-3940",
      "value": "RULE-REST-04: double-booked: P-2202 on 2026-09-15 overlaps the new assignment on 2026-09-15"
    },
    {
      "source": "computed",
      "fact": "excluded C-5392",
      "value": "RULE-REST-04: double-booked: P-2231 on 2026-09-16 overlaps the new assignment on 2026-09-16; RULE-QUAL-05: no A320 rating (holds ATR72)"
    },
    {
      "source": "computed",
      "fact": "excluded C-5647",
      "value": "RULE-REST-04: only 10.5h rest after the new assignment on 2026-09-16, minimum 12h; RULE-REST-04: double-booked: P-2210 on 2026-09-16 overlaps the new assignment on 2026-09-16"
    },
    {
      "source": "computed",
      "fact": "excluded C-5820",
      "value": "RULE-REST-04: only 11.75h rest after the new assignment on 2026-09-17, minimum 12h"
    },
    {
      "source": "computed",
      "fact": "excluded C-5837",
      "value": "RULE-REST-04: only 10.75h rest after the new assignment on 2026-09-17, minimum 12h"
    }
  ],
  "timing_ms": 0
};

export const mockRelaxationResponse: AdvisorResponse = {
  "query": "VT-DXA is delayed 90 minutes on 16 Sep. What should Crew Control do?",
  "intent": "recorded",
  "tier": 3,
  "answer_text": "DX401-2026-09-16 delayed 1.5h; DX402-2026-09-16 delayed 1.5h; DX403-2026-09-16 delayed 1.5h; DX404-2026-09-16 delayed 1.5h. 2026-09-16: FDP 12.75h over 4 sectors, limit 12.0h - exceeds by 0.75h Recommended: Original crew operates DX401-DX403 (delayed); fresh complement operates DX404 at INR 114,000 (cancelling instead costs INR 250,000).",
  "confidence": "high",
  "grounding": {
    "verified": false,
    "unverified_claims": [
      "duration 1.5h was not produced by the rules engine",
      "duration 0.75h was not produced by the rules engine"
    ]
  },
  "impact": {
    "trigger": "DX401-2026-09-16 delayed 1.5h; DX402-2026-09-16 delayed 1.5h; DX403-2026-09-16 delayed 1.5h; DX404-2026-09-16 delayed 1.5h",
    "uncrewed_flights": [],
    "immediate_flights": [],
    "at_risk_flights": [],
    "pairing_broken": [],
    "downstream_risks": [
      {
        "crew_id": "C-3187",
        "rule": "RULE-FDP-01",
        "detail": "2026-09-16: FDP 12.75h over 4 sectors, limit 12.0h - exceeds by 0.75h"
      },
      {
        "crew_id": "C-5375",
        "rule": "RULE-FDP-01",
        "detail": "2026-09-16: FDP 12.75h over 4 sectors, limit 12.0h - exceeds by 0.75h"
      },
      {
        "crew_id": "C-3211",
        "rule": "RULE-FDP-01",
        "detail": "2026-09-16: FDP 12.75h over 4 sectors, limit 12.0h - exceeds by 0.75h"
      },
      {
        "crew_id": "C-2876",
        "rule": "RULE-FDP-01",
        "detail": "2026-09-16: FDP 12.75h over 4 sectors, limit 12.0h - exceeds by 0.75h"
      },
      {
        "crew_id": "C-1542",
        "rule": "RULE-FDP-01",
        "detail": "2026-09-16: FDP 12.75h over 4 sectors, limit 12.0h - exceeds by 0.75h"
      },
      {
        "crew_id": "C-5089",
        "rule": "RULE-FDP-01",
        "detail": "2026-09-16: FDP 12.75h over 4 sectors, limit 12.0h - exceeds by 0.75h"
      }
    ],
    "passengers_affected": 0,
    "graph": {
      "nodes": [
        {
          "id": "DX401-2026-09-16",
          "label": "DX401 +1.5h",
          "type": "flight",
          "status": "at_risk"
        },
        {
          "id": "DX402-2026-09-16",
          "label": "DX402 +1.5h",
          "type": "flight",
          "status": "at_risk"
        },
        {
          "id": "DX403-2026-09-16",
          "label": "DX403 +1.5h",
          "type": "flight",
          "status": "at_risk"
        },
        {
          "id": "DX404-2026-09-16",
          "label": "DX404 +1.5h",
          "type": "flight",
          "status": "at_risk"
        }
      ],
      "edges": [
        {
          "from": "DX401-2026-09-16",
          "to": "DX402-2026-09-16"
        },
        {
          "from": "DX401-2026-09-16",
          "to": "DX403-2026-09-16"
        },
        {
          "from": "DX401-2026-09-16",
          "to": "DX404-2026-09-16"
        },
        {
          "from": "DX402-2026-09-16",
          "to": "DX403-2026-09-16"
        },
        {
          "from": "DX402-2026-09-16",
          "to": "DX404-2026-09-16"
        },
        {
          "from": "DX403-2026-09-16",
          "to": "DX404-2026-09-16"
        }
      ]
    }
  },
  "options": [
    {
      "rank": 1,
      "action": "Original crew operates DX401-DX403 (delayed); fresh complement operates DX404",
      "legal": true,
      "rules_checked": [
        "RULE-FDP-01",
        "RULE-DUTY-02",
        "RULE-FLT-03",
        "RULE-REST-04",
        "RULE-QUAL-05",
        "RULE-CERT-06",
        "RULE-BASE-07"
      ],
      "rule_checks": [],
      "cost_inr": 114000,
      "cost_breakdown": [
        {
          "label": "Callout x 6 crew",
          "amount_inr": 75000
        },
        {
          "label": "Positioning to MAA x 6 crew",
          "amount_inr": 39000
        }
      ],
      "coverage": "all 4 flights",
      "covered_flight_ids": [
        "DX401-2026-09-16",
        "DX402-2026-09-16",
        "DX403-2026-09-16",
        "DX404-2026-09-16"
      ],
      "uncovered_flight_ids": [],
      "delay_minutes": 90,
      "resilience_score": 1.0,
      "resilience_note": "consumes 6 crew for one sector rather than a whole pairing",
      "chain": [],
      "reasoning": "Reduced duty runs 9.5h against a 12.5h limit over 3 sectors, so the rostered crew stay legal. fresh A320 complement (6 crew) operates DX404; DX404 departs MAA, so the complement must be positioned there (INR 39,000)."
    },
    {
      "rank": 2,
      "action": "Cancel DX404",
      "legal": true,
      "rules_checked": [],
      "rule_checks": [],
      "cost_inr": 250000,
      "cost_breakdown": [
        {
          "label": "Cancellation (1 legs x 250,000)",
          "amount_inr": 250000
        }
      ],
      "coverage": "3 of 4 flights",
      "covered_flight_ids": [
        "DX401-2026-09-16",
        "DX402-2026-09-16",
        "DX403-2026-09-16"
      ],
      "uncovered_flight_ids": [
        "DX404-2026-09-16"
      ],
      "delay_minutes": 90,
      "resilience_score": 1.0,
      "resilience_note": "consumes no crew capacity",
      "chain": [],
      "reasoning": "Legal but strands 162 passengers."
    }
  ],
  "evidence": [
    {
      "source": "RULE-FDP-01",
      "fact": "P-2203 delayed duty",
      "value": "12.75h vs 12.0h limit (4 sectors)"
    },
    {
      "source": "RULE-FDP-01",
      "fact": "P-2203 reduced duty",
      "value": "9.5h vs 12.5h limit (3 sectors)"
    },
    {
      "source": "costs.json",
      "fact": "fresh complement callout",
      "value": "114000"
    },
    {
      "source": "costs.json",
      "fact": "cancel DX404",
      "value": "250000"
    }
  ],
  "timing_ms": 0
};
