// GENERATED by backend/scripts/record_fixtures.py -- do not hand-edit.
// Recorded from the live deterministic engine, so offline mode shows real
// dataset facts rather than invented ones. Regenerate after engine changes.

import type { ScorecardResponse } from '../types/api';

export const mockScorecard: ScorecardResponse = {
  "generated_at": "2026-09-05T09:56:36+00:00",
  "total_ms": 574,
  "tiers": [
    {
      "tier": 1,
      "passed": 16,
      "total": 16
    },
    {
      "tier": 2,
      "passed": 14,
      "total": 14
    },
    {
      "tier": 3,
      "passed": 8,
      "total": 8
    }
  ],
  "scenarios": {
    "passed": 6,
    "total": 6
  },
  "cases": [
    {
      "id": "Q01",
      "tier": 1,
      "question": "Who is on reserve at BLR on 2026-09-15, and what are their on-call windows?",
      "passed": true,
      "detail": "12 reserves with matching on-call windows"
    },
    {
      "id": "Q02",
      "tier": 1,
      "question": "As of the snapshot, how many duty hours has C-1042 accrued in the 7 calendar days ending 2026-09-14, and how much headroom does that leave under RULE-DUTY-02?",
      "passed": true,
      "detail": "duty 20.93h, headroom 39.07h"
    },
    {
      "id": "Q03",
      "tier": 1,
      "question": "Which flights depart DEL on 2026-09-15?",
      "passed": true,
      "detail": "departing flights ['DX402'] vs ['DX402']"
    },
    {
      "id": "Q04",
      "tier": 1,
      "question": "List all certifications expiring within 30 days of 2026-09-15.",
      "passed": true,
      "detail": "6 expiring certifications match exactly"
    },
    {
      "id": "Q05",
      "tier": 1,
      "question": "Which aircraft operates DX412 on 2026-09-15, and how many seats does it have?",
      "passed": true,
      "detail": "VT-DXC A320 162 seats vs {'aircraft': 'VT-DXC', 'aircraft_type': 'A320', 'seats': 162}"
    },
    {
      "id": "Q06",
      "tier": 1,
      "question": "What is C-3310's reserve on-call window and reachability?",
      "passed": true,
      "detail": "window 06:00-18:00, 45 min"
    },
    {
      "id": "Q07",
      "tier": 1,
      "question": "What is C-2210's base and rating?",
      "passed": true,
      "detail": "base DEL, ratings ['A320']"
    },
    {
      "id": "Q08",
      "tier": 1,
      "question": "Which crew are assigned to pairing P-2291, and in what roles?",
      "passed": true,
      "detail": "6 crew/role pairs"
    },
    {
      "id": "Q09",
      "tier": 1,
      "question": "Which flights fly BLR→BOM on 2026-09-17?",
      "passed": true,
      "detail": "['DX412', 'DX431'] vs ['DX412', 'DX431']"
    },
    {
      "id": "Q10",
      "tier": 1,
      "question": "How many flights operate on 2026-09-16 in total?",
      "passed": true,
      "detail": "count 21 vs 21"
    },
    {
      "id": "Q11",
      "tier": 1,
      "question": "How many captains are based at DEL, and who are they?",
      "passed": true,
      "detail": "['C-2210'] vs ['C-2210']"
    },
    {
      "id": "Q12",
      "tier": 1,
      "question": "What is the longest block time in the schedule, and which flights have it?",
      "passed": true,
      "detail": "2.75h on ['DX401', 'DX402', 'DX588', 'DX589'] vs 2.75h on ['DX401', 'DX402', 'DX588', 'DX589']"
    },
    {
      "id": "Q13",
      "tier": 1,
      "question": "What is C-2087's rank, and total flight hours over the 28 days ending 2026-09-14?",
      "passed": true,
      "detail": "Captain, 23.5h/28d"
    },
    {
      "id": "Q14",
      "tier": 1,
      "question": "Which stations does the network serve nonstop from BLR?",
      "passed": true,
      "detail": "['BOM', 'CCU', 'COK', 'DEL', 'GOI', 'HYD', 'MAA'] vs ['BOM', 'CCU', 'COK', 'DEL', 'GOI', 'HYD', 'MAA']"
    },
    {
      "id": "Q15",
      "tier": 1,
      "question": "Who is the Senior Cabin Crew on VT-DXB's pairing on 2026-09-16?",
      "passed": true,
      "detail": "SCC ['C-3171'] vs [C-3171]"
    },
    {
      "id": "Q16",
      "tier": 1,
      "question": "What is the disruption-risk score for C-1042 and what drives it?",
      "passed": true,
      "detail": "score 0.78 drivers ['short-rest pattern over last 14 days', 'two fatigue reports this month']"
    },
    {
      "id": "Q17",
      "tier": 2,
      "question": "Captain C-1042 calls in sick at 05:00Z on 15 Sep for pairing P-2291. Which flights are immediately uncrewed?",
      "passed": true,
      "detail": "day1 3 legs / 486 pax, day2 3 at risk"
    },
    {
      "id": "Q18",
      "tier": 2,
      "question": "If Captain C-2087 is assigned to cover P-2291 from 15 Sep, does any rule breach? Give the detail.",
      "passed": true,
      "detail": "illegal with 2 matching DUTY-02 breaches"
    },
    {
      "id": "Q19",
      "tier": 2,
      "question": "BLR is closed 08:00–14:00Z on 17 Sep. Which flights are affected?",
      "passed": true,
      "detail": "13 legs vs 13; diff []"
    },
    {
      "id": "Q20",
      "tier": 2,
      "question": "VT-DXA is delayed 90 minutes before DX401 on 16 Sep. Does the rostered crew breach any limit if they fly all four legs?",
      "passed": true,
      "detail": "2026-09-16: FDP 12.75h over 4 sectors, limit 12.0h - exceeds by 0.75h"
    },
    {
      "id": "Q21",
      "tier": 2,
      "question": "Can C-2210 (DEL base) legally cover P-2291 if positioned to BLR on the morning of 15 Sep? What is the operational consequence?",
      "passed": true,
      "detail": "legal, positioning delay 180 min (expected ~180)"
    },
    {
      "id": "Q22",
      "tier": 2,
      "question": "Can C-5417 legally operate their rostered VT-DXB duty on 19 Sep?",
      "passed": true,
      "detail": "certification invalid on 2026-09-19: recurrent_training (expired 2026-09-17)"
    },
    {
      "id": "Q23",
      "tier": 2,
      "question": "A crew is released at 15:30Z on 16 Sep. What is the earliest they may report next?",
      "passed": true,
      "detail": "2026-09-17T03:30:00 vs 2026-09-17T03:30:00Z"
    },
    {
      "id": "Q24",
      "tier": 2,
      "question": "Can reserve C-3305 cover the FULL pairing P-2291 (both days)? Why or why not?",
      "passed": true,
      "detail": "would exceed 60h/7d by 8h15m on 2026-09-16 (total 68.25h)"
    },
    {
      "id": "Q25",
      "tier": 2,
      "question": "If DX404 on 16 Sep is cancelled, how many passengers are affected and what is the direct cancellation cost?",
      "passed": true,
      "detail": "162 pax, INR 250000"
    },
    {
      "id": "Q26",
      "tier": 2,
      "question": "Which crew have 45 or more duty hours in the 7 days ending 2026-09-15 (including any planned duty that day)?",
      "passed": true,
      "detail": "C-2087 51.83h, C-3305 50.0h"
    },
    {
      "id": "Q27",
      "tier": 2,
      "question": "The VT-DXE captain is sick on 16 Sep (called 01:30Z). Which reserve captains' on-call windows cover the callout, and are they qualified?",
      "passed": true,
      "detail": "eligible ['C-3315']; exclusions match on rule"
    },
    {
      "id": "Q28",
      "tier": 2,
      "question": "Captain C-5837 (VT-DXA line, works 14/17/20 Sep) is proposed to cover P-2291. Legal?",
      "passed": true,
      "detail": "only 10.75h rest after the new assignment on 2026-09-17, minimum 12h"
    },
    {
      "id": "Q29",
      "tier": 2,
      "question": "Station HYD is closed 05:00–09:00Z on 19 Sep. Which flights are affected?",
      "passed": true,
      "detail": "['DX461-2026-09-19', 'DX462-2026-09-19'] vs ['DX461-2026-09-19', 'DX462-2026-09-19']"
    },
    {
      "id": "Q30",
      "tier": 2,
      "question": "Which single flight leg has the most seats at risk if cancelled, and why?",
      "passed": true,
      "detail": "largest leg 162 seats; smallest (ATR72) 72"
    },
    {
      "id": "Q31",
      "tier": 3,
      "question": "Captain C-1042 is out for pairing P-2291 (15–16 Sep). Produce ranked resolution options with costs and reasoning.",
      "passed": true,
      "detail": "top 4 options match on crew and cost, order correct; cancellation last"
    },
    {
      "id": "Q32",
      "tier": 3,
      "question": "Both A320 captains (VT-DXA and VT-DXB) are sick at 00:30Z on 18 Sep. Give the optimal joint crewing plan.",
      "passed": true,
      "detail": "both assignments offered at the key's costs, total 42500"
    },
    {
      "id": "Q33",
      "tier": 3,
      "question": "After the 90-minute delay to VT-DXA on 16 Sep, what should Crew Control do about the FDP breach?",
      "passed": true,
      "detail": "re-crew callout 75000 matches key; total 114000 adds positioning the key omits (documented divergence); cancel 250000 matches"
    },
    {
      "id": "Q34",
      "tier": 3,
      "question": "C-5417's recurrent training lapsed. Resolve their 19 Sep assignment.",
      "passed": true,
      "detail": "top 3 options match on crew and cost, order correct"
    },
    {
      "id": "Q35",
      "tier": 3,
      "question": "BLR closes 08:00–14:00Z on 17 Sep. Outline the recovery plan across affected pairings.",
      "passed": true,
      "detail": "all 13 legs match on delay, FDP, limit and verdict"
    },
    {
      "id": "Q36",
      "tier": 3,
      "question": "Draft the callout notification to C-3310 for covering P-2291.",
      "passed": true,
      "detail": "draft carries all 8 items the key requires"
    },
    {
      "id": "Q37",
      "tier": 3,
      "question": "What is the cheapest legal way to cover the VT-DXF First Officer on 20 Sep if they call sick at 03:30Z?",
      "passed": true,
      "detail": "cheapest: Assign First Officer C-3316 (reserve callout) at 18500 (want C-3316 / 18500)"
    },
    {
      "id": "Q38",
      "tier": 3,
      "question": "If the desk wants a standing morning briefing, which three data points per aircraft line should it surface and why?",
      "passed": true,
      "detail": "briefing surfaces ['cert', 'duty', 'pool', 'risk'] across 11 signals"
    },
    {
      "id": "S1",
      "tier": 3,
      "question": "ATR captain sick call",
      "passed": true,
      "detail": "all 35 expected values present"
    },
    {
      "id": "S2",
      "tier": 3,
      "question": "Flagship: Captain C-1042 sick — 2-day pairing",
      "passed": true,
      "detail": "all 40 expected values present"
    },
    {
      "id": "S3",
      "tier": 3,
      "question": "BLR station closure 08:00–14:00Z, 17 Sep",
      "passed": true,
      "detail": "all 52 expected values present"
    },
    {
      "id": "S4",
      "tier": 3,
      "question": "Tech delay cascades into an FDP breach",
      "passed": true,
      "detail": "all 3 expected values present | DIVERGENCE: Engine costs the tail-leg re-crew at INR 114,000; the answer key says 75,000. The difference is 6 x INR 6,500 deadhead positioning. DX404 departs MAA, every crew member in the dataset is based at BLR or DEL, and there are no MAA-based crew, so a fresh complement must be positioned to MAA (feasible on DX453, arriving 09:00Z against an 11:45Z report). The key omits that cost. Callout subtotal matches the key exactly at 75,000."
    },
    {
      "id": "S5",
      "tier": 3,
      "question": "Certification lapse discovered pre-flight",
      "passed": true,
      "detail": "all 69 expected values present"
    },
    {
      "id": "S6",
      "tier": 3,
      "question": "Two simultaneous captain sick calls",
      "passed": true,
      "detail": "all 30 expected values present"
    }
  ]
};
